### ISSUE TITLE
update for mercurial 6.0

### ISSUE THREAD

**Issue by mattip** [conda-forge/mercurial-feedstock#47]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Mercurial 6.0 [was released](https://www.mercurial-scm.org/wiki/Release6.0) in Nov 2021. Should the feedstock be updated?

**Comment by paugier** [comment]
I don't understand why no PR was created automatically for Mercurial 6.0.

I just merged the PR for Mercurial 6.0.1 https://github.com/conda-forge/mercurial-feedstock/pull/48 so this version should be available soon.

**Comment by mattip** [comment]
Thanks!

**Comment by jakirkham** [comment]
If they came out close together, the bot would have just picked the latest version
